### ISSUE TITLE
image-filters:blur does not work as expected

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#1263]
Its quite nice looking, but does not appear blurred (agg-stack-blur does work):

<img src="http://f.cl.ly/items/3a1f0J2e113t261d3m0V/t.png" />

done with:

``` css
Map {
  background-color: steelblue;
}

#countries {
  polygon-fill: green;
  image-filters:blur;
}
```
