### ISSUE TITLE
MarkersSymbolizer expression only takes effect after a TextSymbolizer

### ISSUE THREAD

**Issue by sethfitz** [mapnik/mapnik#2089]
``` xml
<Style name="poi_label" filter-mode="first">
  <Rule>
    <TextSymbolizer face-name="Source Sans Pro Regular" ><![CDATA[[maki]]]></TextSymbolizer>
    <MarkersSymbolizer file="images/[maki]-18.svg" />
  </Rule>
</Style>
```

...correctly looks for `images/<name>-18.svg` (`<name>` will occasionally be blank) while

``` xml
<Style name="poi_label" filter-mode="first">
  <Rule>
    <MarkersSymbolizer file="images/[maki]-18.svg" />
  </Rule>
</Style>
```

reliably looks for `images/-18.svg` (no `<name>`).

(Mapnik 2.2 via tm2 HEAD)

CartoCSS resulting in this behavior:

``` css
#poi_label {
  text-face-name: "Source Sans Pro Regular";
  text-name: [maki];
  marker-file: url("images/[maki]-18.svg");
}
```

``` css
#poi_label {
  marker-file: url("images/[maki]-18.svg");
}
```
