### ISSUE TITLE
SVG masks not honored

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#2281]
With the following SVG, the mask is not honored.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" height="100%" viewBox="0 0 16 16">
<defs>
<mask id="innercutout">
<rect x="0" y="0" width="16" height="16" fill="white"/>
<circle cx="8" cy="8" r="4"/>
</mask>
</defs>

<g id="petals" mask="url(#innercutout)">
<rect x="0" y="0" width="16" height="16" rx="3"/>
</g>
</svg>
```

The result is
![44900](https://cloud.githubusercontent.com/assets/1190866/3352262/2e8f249c-fa3d-11e3-903e-189a9d6def3a.png)

with the MSS 

``` css
  [shop = 'car'][zoom >= 17]::shop {
    marker-file: url('symbols/mask_test.svg');
    marker-placement: interior;
    marker-clip: false;
  }
```

Viewed in Chrome, the SVG looks like this
![image](https://cloud.githubusercontent.com/assets/1190866/3352267/60d794ca-fa3d-11e3-8bd3-f4d642167db5.png)
