### ISSUE TITLE
translate( x,y) doesn't scale

### ISSUE THREAD

**Issue by samanpwbb** [mapnik/mapnik#2572]
Here's a gif, with @2x tiles scaled down to half size for better comparison:

![screen-shot-2014-11-12-at-4 11 29-pm](https://cloud.githubusercontent.com/assets/108094/5018821/04b29364-6a88-11e4-8293-af1ec7f1970e.gif)

My marker is getting offset `120px` on both standard and retina, which results in double distance on standard screens. Here's the code:

``` css
  [graphic='statue of liberty'] {
    marker-file: url(statueofliberty.svg);
    marker-transform: translate(-120,0);
}
```

This is in contrast to the behavior of, say, `text-dx` which is correctly scaled for visual parity between retina and non-retina.

Is this supposed to scale?
