### ISSUE TITLE
Point markers clipped at tile boundary

### ISSUE THREAD

**Issue by knutole** [mapnik/mapnik#2873]
Markers get clipped at tile boundaries, and setting `buffer_size` on either `Map` or `vtile.render()` doesn't seem to do much. Could perhaps be related to #2577, or be due to something else? Is there a fix for this?

![screen shot 2015-05-26 at 23 45 53](https://cloud.githubusercontent.com/assets/2197944/7824228/9a188c70-0401-11e5-8443-46b4effd263e.png)

```css
Map {
	buffer-size: 256;
}

#layer {
		marker-fill: #001980;
		marker-allow-overlap: true;
		marker-comp-op: screen;
  		marker-clip: false;
  		marker-width: [DTOTAL] / "@DTOTALMAX";
}
```

```javascript
var options = {
	buffer_size : 256,
};

vtile.render(map, new mapnik.Image(256,256), options, callback);

```
